"""Writers for the Roblox side: Luau modules and an .rbxmx model file to insert in Studio."""

from __future__ import annotations

import math
import os
import re
import uuid
from xml.sax.saxutils import escape

TEMPLATES = os.path.join(os.path.dirname(__file__), "templates")
_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_LUAU_KEYWORDS = {
    "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "if", "in",
    "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while", "continue",
}  # fmt: skip


def to_luau(value, indent: int = 0, compact: bool = False) -> str:
    """Python data -> Luau literal (dicts become tables, None values are dropped)."""
    pad = "" if compact else "\t" * (indent + 1)
    end_pad = "" if compact else "\t" * indent
    sep = ", " if compact else ",\n"
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return "0"
        text = f"{value:.4f}".rstrip("0").rstrip(".")
        return text if text not in ("-0", "") else "0"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "")
        return f'"{escaped}"'
    if isinstance(value, (list, tuple)):
        if not value:
            return "{}"
        simple = all(not isinstance(v, (list, tuple, dict)) for v in value)
        if simple or compact:
            return "{ " + ", ".join(to_luau(v, 0, True) for v in value) + " }"
        items = [pad + to_luau(v, indent + 1, compact) for v in value]
        return "{" + ("" if compact else "\n") + sep.join(items) + ("" if compact else ",\n") + end_pad + "}"
    if isinstance(value, dict):
        items = []
        for k, v in value.items():
            if v is None:
                continue
            key = k if (isinstance(k, str) and _IDENT.match(k) and k not in _LUAU_KEYWORDS) else f"[{to_luau(k)}]"
            items.append(f"{pad}{key} = {to_luau(v, indent + 1, compact)}")
        if not items:
            return "{}"
        if compact:
            return "{ " + ", ".join(i.strip() for i in items) + " }"
        return "{\n" + ",\n".join(items) + ",\n" + end_pad + "}"
    raise TypeError(f"cannot convert {type(value).__name__} to Luau")


def manifest_module(manifest: dict) -> str:
    objects = [
        {
            "name": o["name"],
            "category": o["category"],
            "center": o["center"],
            "size": o["size"],
            "color": o.get("color"),
            "invisible": o.get("invisible") or None,
        }
        for o in manifest["objects"]
    ]
    data = {
        "track": manifest["track"],
        "layout": manifest.get("layout"),
        "studsPerMeter": round(manifest["studs_per_meter"], 5),
        "offset": manifest["offset"],
        "styles": manifest["styles"],
    }
    lines = ["-- Generated by tools/assetto/ac2roblox.py: what the converter produced.", "local Manifest = " + to_luau(data)]
    lines.append("Manifest.objects = {")
    for o in objects:
        lines.append("\t" + to_luau(o, 1, compact=True) + ",")
    lines.append("}")
    lines.append("return Manifest")
    return "\n".join(lines) + "\n"


def racing_line_module(line: dict | None) -> str:
    header = "-- Racing line from ai/fast_lane.ai: { x, y, z, left, right } in studs.\n"
    if not line:
        return header + "return { closed = false, points = {} }\n"
    rows = ",\n".join("\t\t" + to_luau(p, 0, True) for p in line["points"])
    return (
        header
        + "return {\n"
        + f"\tclosed = {to_luau(line['closed'])},\n"
        + f"\tlengthMeters = {to_luau(line['length_m'])},\n"
        + "\tpoints = {\n"
        + rows
        + ",\n\t},\n}\n"
    )


def tools_module() -> str:
    with open(os.path.join(TEMPLATES, "Tools.luau"), encoding="utf-8") as f:
        return f.read()


def _cdata(text: str) -> str:
    return "<![CDATA[" + text.replace("]]>", "]]]]><![CDATA[>") + "]]>"


def write_rbxmx(path: str, folder_name: str, modules: dict) -> None:
    """A model file with one Folder holding ModuleScripts (Insert from File in Studio)."""

    def ref():
        return "RBX" + uuid.uuid4().hex.upper()

    out = [
        '<roblox xmlns:xmime="http://www.w3.org/2005/05/xmlmime" '
        'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
        'xsi:noNamespaceSchemaLocation="http://www.roblox.com/roblox.xsd" version="4">',
        f'\t<Item class="Folder" referent="{ref()}">',
        "\t\t<Properties>",
        f'\t\t\t<string name="Name">{escape(folder_name)}</string>',
        "\t\t</Properties>",
    ]
    for name, source in modules.items():
        out += [
            f'\t\t<Item class="ModuleScript" referent="{ref()}">',
            "\t\t\t<Properties>",
            f'\t\t\t\t<string name="Name">{escape(name)}</string>',
            f'\t\t\t\t<ProtectedString name="Source">{_cdata(source)}</ProtectedString>',
            "\t\t\t</Properties>",
            "\t\t</Item>",
        ]
    out += ["\t</Item>", "</roblox>", ""]
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))


def write_roblox_files(out_dir: str, manifest: dict, line: dict | None) -> str:
    folder_name = manifest["track"] + "_AC"
    modules = {
        "Tools": tools_module().replace("<Folder>", folder_name),
        "Manifest": manifest_module(manifest),
        "RacingLine": racing_line_module(line),
    }
    luau_dir = os.path.join(out_dir, "luau")
    os.makedirs(luau_dir, exist_ok=True)
    for name, source in modules.items():
        with open(os.path.join(luau_dir, name + ".luau"), "w", encoding="utf-8", newline="\n") as f:
            f.write(source)
    path = os.path.join(out_dir, folder_name + ".rbxmx")
    write_rbxmx(path, folder_name, modules)
    return path


def render_preview(out_path: str, geoms, manifest: dict, size: int = 1600) -> bool:
    """Top-down picture of the converted track (road/kerb/... colours + racing line).

    Compare it with the track's map.png: if it looks mirrored, convert again with --mirror.
    Needs Pillow; returns False when it is not installed."""
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        return False
    x0, _, z0, x1, _, z1 = manifest["bounds"]
    span = max(x1 - x0, z1 - z0, 1.0)
    pad = span * 0.03
    scale = size / (span + 2 * pad)
    w = int((x1 - x0 + 2 * pad) * scale) + 1
    h = int((z1 - z0 + 2 * pad) * scale) + 1
    img = Image.new("RGB", (w, h), (18, 22, 30))
    draw = ImageDraw.Draw(img)
    order = ["ground", "grass", "sand", "building", "wall", "kerb", "road"]
    styles = manifest["styles"]
    for category in order:
        color = tuple(styles.get(category, styles["building"])["color"])
        if category == "road":
            color = (120, 120, 130)
        for g in geoms:
            if g.category != category or g.invisible:
                continue
            p, idx = g.positions, g.indices
            for t in range(0, len(idx) - 2, 3):
                a, b, c = idx[t], idx[t + 1], idx[t + 2]
                pts = [((p[3 * k] - x0 + pad) * scale, (p[3 * k + 2] - z0 + pad) * scale) for k in (a, b, c)]
                draw.polygon(pts, fill=color)
    line = manifest.get("racing_line")
    if line and line["points"]:
        pts = [((q[0] - x0 + pad) * scale, (q[2] - z0 + pad) * scale) for q in line["points"]]
        if line["closed"]:
            pts.append(pts[0])
        draw.line(pts, fill=(0, 230, 255), width=max(1, size // 600))
        sx, sy = pts[0]
        draw.ellipse([sx - 5, sy - 5, sx + 5, sy + 5], fill=(255, 255, 255))
    img.save(out_path)
    return True
